Fix createdAt metadata for missing published_at
Possibly for when staff was looking at an unpublished work page?  We were getting `NoMethodError: undefined method `iso8601' for nil`. Easy to fix.